dbParams:
  host: 127.0.0.1
  user: <user>
  password: <password>
  database: <database>

serverParams:
  PORT: 3000
  JWT_ACCESS_SECRET: <jwt-secret-key>
  JWT_REFRESH_SECRET: <jwt-refresh-secret-key>
  CLIENT_URL: <http://localhost:8080>